name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and Push Docker Images
        run: |
          docker build -t dollu/the-alter-office-backend .
          docker push dollu/the-alter-office-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Stop and Remove Old Containers
        run: |
          docker stop the-alter-office-backend-container || true
          docker rm the-alter-office-backend-container || true
      - name: Pull Latest Backend Image
        run: |
          docker pull dollu/the-alter-office-backend:latest

      - name: Run Backend Container
        run: |
          docker run -d -p 3000:3000 --name the-alter-office-backend-container \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            dollu/the-alter-office-backend
